const DEMO_MODE = true;

const CROWD_ZONES = [
  { zoneId: 'Z-LOBBY', label: 'Lobby', floor: 'G', location: 'LOBBY' },
  { zoneId: 'Z-REST', label: 'Restaurant', floor: 'G', location: 'RESTAURANT' },
  { zoneId: 'Z-BAR', label: 'Bar / Lounge', floor: 'G', location: 'BAR' },
  { zoneId: 'Z-POOL', label: 'Pool / Spa', floor: '1', location: 'POOL' },
  { zoneId: 'Z-GYM', label: 'Gym', floor: '1', location: 'GYM' },
  { zoneId: 'Z-CLUB', label: 'Clubhouse', floor: '1', location: 'CLUBHOUSE' },
  { zoneId: 'Z-PARK', label: 'Parking', floor: 'B1', location: 'PARKING' },
  { zoneId: 'Z-GARD', label: 'Garden', floor: 'G', location: 'GARDEN' },
  { zoneId: 'Z-CORR3', label: 'Corridor FL3', floor: '3', location: 'CORRIDOR' },
  { zoneId: 'Z-CORR7', label: 'Corridor FL7', floor: '7', location: 'CORRIDOR' },
];

let warnings = [];
let engineInterval = null;

// Initialize zone data state
let zoneData = CROWD_ZONES.map(zone => ({
  ...zone,
  density: 0,
  temperature: 25,
  previousDensity: 0,
  riskLevel: 'LOW',
  trend: 'STABLE',
  lastUpdated: new Date().toISOString()
}));

function calculateRisk(density, temperature) {
  if (density > 50 || temperature > 35) return 'HIGH';
  if (density > 30) return 'MEDIUM';
  return 'LOW';
}

function calculateTrend(current, previous) {
  if (current > previous + 5) return 'INCREASING';
  if (current < previous - 5) return 'DECREASING';
  return 'STABLE';
}

function generateWarning(zone) {
  const warning = {
    type: 'CROWD_SURGE',
    zoneId: zone.zoneId,
    location: zone.location,
    floor: zone.floor,
    severity: 'MEDIUM',
    warningLevel: 'HIGH',
    description: `High crowd density at ${zone.label}. Prepare to redirect guests.`,
    timestamp: new Date().toISOString(),
    status: 'WARNING',
    autoGenerated: true
  };
  
  if (DEMO_MODE) {
    warnings.push(warning);
    console.log(`[CrowdEngine] WARNING Generated for ${zone.label}: Density ${zone.density}, Temp ${zone.temperature}`);
  }
}

function updateSensors() {
  zoneData.forEach(zone => {
    zone.previousDensity = zone.density;
    
    // Simulate sensor data: density 10-80, temperature 25-38
    zone.density = Math.floor(Math.random() * 71) + 10;
    zone.temperature = Math.floor(Math.random() * 14) + 25;
    
    const newRiskLevel = calculateRisk(zone.density, zone.temperature);
    zone.trend = calculateTrend(zone.density, zone.previousDensity);
    zone.lastUpdated = new Date().toISOString();
    
    // Generate warning if transitioned to HIGH risk
    if (newRiskLevel === 'HIGH' && zone.riskLevel !== 'HIGH') {
      generateWarning(zone);
    }
    
    zone.riskLevel = newRiskLevel;
  });
}

function startCrowdEngine() {
  if (engineInterval) return;
  console.log('[CrowdEngine] Starting sensor simulation every 4 seconds...');
  // Initial run
  updateSensors();
  // Loop
  engineInterval = setInterval(updateSensors, 4000);
}

function getCrowdZones() {
  return zoneData;
}

function simulateSurge(zoneId) {
  const zone = zoneData.find(z => z.zoneId === zoneId);
  if (!zone) return { error: 'Zone not found' };

  zone.previousDensity = zone.density;
  zone.density = 75; // Force high density
  zone.temperature = 36; // Force high temp
  
  const newRiskLevel = calculateRisk(zone.density, zone.temperature);
  zone.trend = calculateTrend(zone.density, zone.previousDensity);
  zone.lastUpdated = new Date().toISOString();
  
  if (newRiskLevel === 'HIGH' && zone.riskLevel !== 'HIGH') {
    generateWarning(zone);
  }
  
  zone.riskLevel = newRiskLevel;
  console.log(`[CrowdEngine] Simulated surge for ${zone.label}`);
  return zone;
}

function getCrowdWarnings() {
  return warnings;
}

module.exports = {
  startCrowdEngine,
  getCrowdZones,
  simulateSurge,
  getCrowdWarnings
};
